### ISSUE TITLE
Make the wordLibrary variable into a .txt file

### ISSUE THREAD

**Issue by delivey** [QwertyAswal/disappearing_man#9]
Hey, just noticed that the movies are stored in a variable called: `wordLibrary`
```
wordLibrary = ["Vikram Vedha", "Taare Zameen Par", "Andhadhun", "Bhaag Milkha Bhaag", "Jo Jeeta Wohi Sikandar",
               "Paan Singh Tomar", "Rang De Basanti", "Gangs of Wasseypur", "A Wednesday", "Dil Chahta Hai",
               "Zindagi Na Milegi Dobara", "Lage Raho Munna Bhai", "Baahubali", "Bajrangi Bhaijaan", "Gangaajal"]
```
I think this is inefficient, because you have to add new movies in the .py file. My suggestion is this:

- Have a .txt file where all the movie names would be stored in separate lines.
- Access the .txt file from the script and load the movie names into the script.

I think I could do this, is that ok?

**Comment by QwertyAswal** [comment]
Ya sure

**Comment by delivey** [comment]
Closing this issue as I added it in #10.
